# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 1d64414fcc7659de87347fa7e767d7ddb9cefbcf

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        host: smtp.qq.com
        port: 25
        user: 1136546636
        password: 8001711046LXH
        protocol: smtp
        tls: false
        auth: false
        from: 1136546636@qq.com

    messageSource:
        cacheSeconds: 1

swagger:
    title: online_exam_system API
    description: online_exam_system applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
